name: Run tests on pull request

on: pull_request

# PHP version's patch number gets ignored even if you write it down, note that the tests locally will run on a different
# PHP patch compared to those in GitHub Actions.

jobs:
  tests-and-analyse:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
        stability:
          - "prefer-lowest"
          - "prefer-stable"
    steps:
      - name: Check out the code so Composer can see our private composer.json file and more
        timeout-minutes: 1
        uses: actions/checkout@v4.1.7

      - name: Setup PHP with tools
        timeout-minutes: 1
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          ini-values: zend.exception_ignore_args="0", date.timezone="Europe/Amsterdam"
          # Start with none to disable default, include all from `make php-modules`.
          # Do not include `cli`, `common` or `fpm`.
          # We replace mysql with mysqlnd and pdo_mysql.
          # Also include the ext's from your composer.json, you should also have them enabled (not installed).
          extensions: none, Core, ctype, curl, date, dom, fileinfo, filter, ftp, hash, iconv, json, libxml, mbstring, mysqlnd, openssl, pcre, PDO, pdo_sqlite, Phar, posix, readline, Reflection, session, SimpleXML, sodium, SPL, sqlite3, standard, tokenizer, xml, xmlreader, xmlwriter, zlib

      - name: Run Composer install
        timeout-minutes: 1
        run: composer install --no-interaction

      - name: Raise the PHP version
        timeout-minutes: 1
        run: composer require php:~${{ matrix.php-version }} --no-interaction --no-update

      - name: Run composer update
        timeout-minutes: 1
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --with-all-dependencies

      - name: Run unit tests
        timeout-minutes: 1
        run: vendor/bin/phpunit tests --testdox

      - name: Run PHPStan analyze for everything
        timeout-minutes: 1
        run: vendor/bin/phpstan analyse --configuration=phpstan-all.neon

      - name: Run PHPStan analyze for everything but cs fixer
        timeout-minutes: 1
        run: vendor/bin/phpstan analyse --configuration=phpstan-not-cs-fixer.neon

      - name: Run PHPStan analyze for everything but tests
        timeout-minutes: 1
        run: vendor/bin/phpstan analyse --configuration=phpstan-not-tests.neon
